#!/usr/bin/env bash
# ACOS Linux desktop installer (architecture 68, 74; handoff "usable installed app").
#
# Installs ACOS from this checkout as a per-user desktop application: a launcher on
# PATH, a freedesktop .desktop entry, and an icon. Idempotent, so re-running is an
# upgrade. `--uninstall` removes the launcher/entry/icon and, with `--purge`, the
# companion data directory too.
#
# Everything is installed under ${ACOS_PREFIX:-$HOME/.local} so no root is needed.
set -euo pipefail

usage() {
  cat <<'EOF'
ACOS Linux installer

Usage:
  bash src/host/install-linux.sh [--prefix DIR] [--build] [--uninstall [--purge]] [--help]

Options:
  --prefix DIR   Install root (default: ${ACOS_PREFIX:-$HOME/.local})
  --build        Force a dashboard rebuild even if dist/ already exists
  --uninstall    Remove the launcher, desktop entry and icon
  --purge        With --uninstall, also delete the companion data directory
  --help         Show this message

The installer never edits your shell profile and never needs root. It keeps the
companion database and administrator key in ${ACOS_DATA_DIR:-$HOME/.local/share/acos}.
EOF
}

prefix="${ACOS_PREFIX:-$HOME/.local}"
data_dir="${ACOS_DATA_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/acos}"
force_build=0
uninstall=0
purge=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --prefix) prefix="${2:?--prefix needs a directory}"; shift 2 ;;
    --build) force_build=1; shift ;;
    --uninstall) uninstall=1; shift ;;
    --purge) purge=1; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"
app_name="acos"
launcher_dir="$prefix/bin"
launcher="$launcher_dir/$app_name"
applications_dir="$prefix/share/applications"
desktop_file="$applications_dir/$app_name.desktop"
icon_dir="$prefix/share/icons/hicolor/scalable/apps"
icon_file="$icon_dir/$app_name.svg"

if [[ "$uninstall" -eq 1 ]]; then
  rm -f -- "$launcher" "$desktop_file" "$icon_file"
  echo "Removed ACOS launcher, desktop entry and icon from $prefix."
  if [[ "$purge" -eq 1 ]]; then
    rm -rf -- "$data_dir"
    echo "Purged companion data directory $data_dir."
  else
    echo "Companion data preserved at $data_dir (use --purge to delete it)."
  fi
  command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database "$applications_dir" 2>/dev/null || true
  exit 0
fi

# --- Preflight -------------------------------------------------------------
if [[ "$(uname -s)" != Linux ]]; then
  echo "This installer targets Linux. Windows setup: docs/windows.md." >&2
  exit 1
fi
if [[ "$EUID" -eq 0 ]]; then
  echo "Run as your normal user, not root. ACOS installs per-user." >&2
  exit 1
fi
if [[ ! -f "$repo_dir/package.json" ]]; then
  echo "Run this script from inside the ACOS checkout." >&2
  exit 1
fi

# Bring the pinned toolchain onto PATH if setup already provisioned it.
# shellcheck source=/dev/null
source "$repo_dir/src/host/toolchain.sh"
node_bin="$(command -v node || true)"
if [[ -z "$node_bin" ]]; then
  echo "Node 24+ is required. Run 'bash src/host/setup-wsl.sh' first." >&2
  exit 1
fi
node_major="$("$node_bin" -e 'process.stdout.write(process.versions.node.split(".")[0])')"
if [[ "$node_major" -lt 24 ]]; then
  echo "Node 24+ is required (found $("$node_bin" --version))." >&2
  exit 1
fi

# --- Build the dashboard ---------------------------------------------------
if [[ "$force_build" -eq 1 || ! -f "$repo_dir/dist/index.html" ]]; then
  if ! command -v pnpm >/dev/null 2>&1; then
    echo "pnpm is required to build the dashboard. Run 'bash src/host/setup-wsl.sh' first." >&2
    exit 1
  fi
  echo "Building the ACOS dashboard..."
  ( cd "$repo_dir" && pnpm build )
fi

# --- Install launcher ------------------------------------------------------
mkdir -p "$launcher_dir" "$applications_dir" "$icon_dir"
cat > "$launcher" <<EOF
#!/usr/bin/env bash
# Generated by ACOS install-linux.sh. Launches the installed ACOS workspace.
set -euo pipefail
exec bash "$repo_dir/src/host/start-local.sh" "\$@"
EOF
chmod 0755 "$launcher"

# --- Install icon ----------------------------------------------------------
cat > "$icon_file" <<'EOF'
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" width="256" height="256">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#0f766e"/>
      <stop offset="1" stop-color="#065f46"/>
    </linearGradient>
  </defs>
  <rect width="256" height="256" rx="56" fill="url(#g)"/>
  <circle cx="128" cy="128" r="74" fill="none" stroke="#ecfdf5" stroke-width="10" opacity="0.85"/>
  <circle cx="128" cy="128" r="30" fill="#ecfdf5"/>
  <path d="M128 54v30M128 172v30M54 128h30M172 128h30" stroke="#ecfdf5" stroke-width="10" stroke-linecap="round"/>
</svg>
EOF

# --- Install desktop entry -------------------------------------------------
cat > "$desktop_file" <<EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=ACOS
GenericName=AI Companion
Comment=Local AI companion with explicit capability policy
Exec=$launcher
Icon=$app_name
Terminal=true
Categories=Utility;ArtificialIntelligence;
Keywords=AI;Companion;Assistant;Local;
StartupNotify=true
EOF

command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database "$applications_dir" 2>/dev/null || true

echo "ACOS installed."
echo "  Launcher:      $launcher"
echo "  Desktop entry: $desktop_file"
echo "  Icon:          $icon_file"
echo "  Data:          $data_dir"
case ":$PATH:" in
  *":$launcher_dir:"*) ;;
  *) echo "  Note: add $launcher_dir to your PATH to run 'acos' from a terminal." ;;
esac
echo "Launch ACOS from your application menu, or run: $launcher"
