#!/usr/bin/env bash
# ACOS macOS desktop installer (architecture 68, 74; handoff "usable installed app").
#
# Installs ACOS from this checkout as a per-user desktop application on macOS:
#   * an ACOS.app bundle in ~/Applications (double-clickable, shows in Launchpad),
#   * a CLI launcher on PATH (~/.local/bin/acos),
#   * optionally a per-user LaunchAgent so ACOS starts at login (--login-item).
#
# Idempotent: re-running is an upgrade. `--uninstall` removes the bundle, launcher
# and login item; `--purge` additionally deletes the companion data directory.
#
# Everything installs under ${ACOS_PREFIX:-$HOME/.local} and ~/Applications, so no
# root is needed. The engine is confined with Seatbelt (sandbox-exec) + ulimit via
# the host's Darwin isolation adapter; see docs/macos.md.
set -euo pipefail

usage() {
  cat <<'EOF'
ACOS macOS installer

Usage:
  bash src/macos/install-macos.sh [--prefix DIR] [--build] [--login-item]
                                  [--uninstall [--purge]] [--dry-run] [--help]

Options:
  --prefix DIR   Install root for the CLI launcher (default: ${ACOS_PREFIX:-$HOME/.local})
  --build        Force a dashboard rebuild even if dist/ already exists
  --login-item   Install a per-user LaunchAgent so ACOS starts at login
  --uninstall    Remove the app bundle, CLI launcher and login item
  --purge        With --uninstall, also delete the companion data directory
  --dry-run      Print every action without changing anything
  --help         Show this message

The installer never edits your shell profile and never needs root. It keeps the
companion database and administrator key in ${ACOS_DATA_DIR:-$HOME/.local/share/acos}.
EOF
}

prefix="${ACOS_PREFIX:-$HOME/.local}"
data_dir="${ACOS_DATA_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/acos}"
apps_dir="${ACOS_APPS_DIR:-$HOME/Applications}"
force_build=0
login_item=0
uninstall=0
purge=0
dry_run=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --prefix) prefix="${2:?--prefix needs a directory}"; shift 2 ;;
    --build) force_build=1; shift ;;
    --login-item) login_item=1; shift ;;
    --uninstall) uninstall=1; shift ;;
    --purge) purge=1; shift ;;
    --dry-run) dry_run=1; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

run() {
  if [[ "$dry_run" -eq 1 ]]; then echo "[dry-run] $*"; else "$@"; fi
}

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"
app_name="acos"
launcher_dir="$prefix/bin"
launcher="$launcher_dir/$app_name"
app_bundle="$apps_dir/ACOS.app"
agent_label="com.acos.host"
agent_plist="$HOME/Library/LaunchAgents/$agent_label.plist"

if [[ "$uninstall" -eq 1 ]]; then
  run rm -rf -- "$app_bundle"
  run rm -f -- "$launcher"
  if [[ -f "$agent_plist" ]]; then
    run launchctl bootout "gui/$(id -u)/$agent_label" 2>/dev/null || true
    run rm -f -- "$agent_plist"
  fi
  echo "Removed ACOS app bundle, CLI launcher and login item."
  if [[ "$purge" -eq 1 ]]; then
    run rm -rf -- "$data_dir"
    echo "Purged companion data directory $data_dir."
  else
    echo "Companion data preserved at $data_dir (use --purge to delete it)."
  fi
  exit 0
fi

# --- Preflight -------------------------------------------------------------
if [[ "$(uname -s)" != Darwin ]]; then
  echo "This installer targets macOS. Linux: docs/install-linux.md; Windows: docs/windows.md." >&2
  exit 1
fi
if [[ "$EUID" -eq 0 ]]; then
  echo "Run as your normal user, not root. ACOS installs per-user." >&2
  exit 1
fi
if [[ ! -f "$repo_dir/package.json" ]]; then
  echo "Run this script from inside the ACOS checkout." >&2
  exit 1
fi

# Bring the pinned toolchain onto PATH if setup already provisioned it.
# shellcheck source=/dev/null
source "$repo_dir/src/host/toolchain.sh"
node_bin="$(command -v node || true)"
if [[ -z "$node_bin" ]]; then
  echo "Node 24+ is required. Install it (e.g. 'brew install node@24') and retry." >&2
  exit 1
fi
node_major="$("$node_bin" -e 'process.stdout.write(process.versions.node.split(".")[0])')"
if [[ "$node_major" -lt 24 ]]; then
  echo "Node 24+ is required (found $("$node_bin" --version))." >&2
  exit 1
fi

# --- Build the dashboard ---------------------------------------------------
if [[ "$force_build" -eq 1 || ! -f "$repo_dir/dist/index.html" ]]; then
  if ! command -v pnpm >/dev/null 2>&1; then
    echo "pnpm is required to build the dashboard. Install it ('corepack enable pnpm') and retry." >&2
    exit 1
  fi
  echo "Building the ACOS dashboard..."
  ( cd "$repo_dir" && pnpm build )
fi

# --- Install CLI launcher --------------------------------------------------
run mkdir -p "$launcher_dir"
cat > "$launcher" <<EOF
#!/usr/bin/env bash
# Generated by ACOS install-macos.sh. Launches the installed ACOS workspace.
set -euo pipefail
exec bash "$repo_dir/src/host/start-local.sh" "\$@"
EOF
run chmod 0755 "$launcher"

# --- Install app bundle ----------------------------------------------------
run mkdir -p "$app_bundle/Contents/MacOS" "$app_bundle/Contents/Resources"
cat > "$app_bundle/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>ACOS</string>
  <key>CFBundleDisplayName</key><string>ACOS</string>
  <key>CFBundleIdentifier</key><string>$agent_label</string>
  <key>CFBundleVersion</key><string>0.1.0</string>
  <key>CFBundleShortVersionString</key><string>0.1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>LSMinimumSystemVersion</key><string>13.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>LSUIElement</key><false/>
</dict>
</plist>
EOF
cat > "$app_bundle/Contents/MacOS/ACOS" <<EOF
#!/usr/bin/env bash
# Generated by ACOS install-macos.sh. Opens the ACOS workspace in Terminal so the
# host log stays visible; Ctrl-C stops the host and dashboard together.
set -euo pipefail
exec /usr/bin/osascript -e 'tell application "Terminal" to do script "bash $repo_dir/src/host/start-local.sh"' -e 'tell application "Terminal" to activate'
EOF
run chmod 0755 "$app_bundle/Contents/MacOS/ACOS"

# --- Optional login item ---------------------------------------------------
if [[ "$login_item" -eq 1 ]]; then
  run mkdir -p "$(dirname "$agent_plist")"
  cat > "$agent_plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$agent_label</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$repo_dir/src/host/start-local.sh</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><false/>
  <key>StandardOutPath</key><string>$data_dir/acos-host.log</string>
  <key>StandardErrorPath</key><string>$data_dir/acos-host.log</string>
</dict>
</plist>
EOF
  run launchctl bootout "gui/$(id -u)/$agent_label" 2>/dev/null || true
  run launchctl bootstrap "gui/$(id -u)" "$agent_plist"
  echo "Installed login item $agent_label (starts ACOS at login)."
fi

echo "ACOS installed."
echo "  App bundle:  $app_bundle"
echo "  Launcher:    $launcher"
echo "  Data:        $data_dir"
case ":$PATH:" in
  *":$launcher_dir:"*) ;;
  *) echo "  Note: add $launcher_dir to your PATH to run 'acos' from a terminal." ;;
esac
echo "Open ACOS from Launchpad/Applications, or run: $launcher"
