# ACOS Windows 11 installer (handoff: "usable installed Windows 11 application").
#
# This script automates the whole first-run path on a fresh Windows 11 machine:
#   1. Verifies Windows 11 and enables the WSL2 feature if needed.
#   2. Installs the Ubuntu-24.04 distribution.
#   3. Clones or updates the ACOS repository inside the Linux home.
#   4. Runs the Linux setup (pinned Node/pnpm, dependencies, dashboard build).
#   5. Creates Start Menu and Desktop shortcuts plus a launcher.
#
# Run in an elevated PowerShell:  powershell -ExecutionPolicy Bypass -File Install-ACOS.ps1
#
# NOTE: This script is authored for Windows and is NOT executed in the Linux
# development sandbox. See docs/windows.md ("Verification scope"). The Linux side
# it drives (setup-wsl.sh, start-local.sh) is tested in the sandbox.

[CmdletBinding()]
param(
  [string]$Distro = "Ubuntu-24.04",
  [string]$RepoUrl = "https://github.com/corenetworkadmin-gif/acos-dashboard.git",
  [string]$InstallDir = "~/acos-dashboard",
  [switch]$SkipSetup
)

$ErrorActionPreference = "Stop"

function Assert-Admin {
  $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
  $principal = New-Object Security.Principal.WindowsPrincipal($identity)
  if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw "Run this installer from an elevated (Administrator) PowerShell window."
  }
}

function Test-Windows11 {
  $build = [System.Environment]::OSVersion.Version.Build
  if ($build -lt 22000) {
    throw "ACOS targets Windows 11 (build 22000+). Detected build $build."
  }
}

function Get-WslDistros {
  try {
    # wsl.exe emits UTF-16; decode explicitly.
    $raw = & wsl.exe --list --quiet 2>$null
    if ($LASTEXITCODE -ne 0) { return @() }
    return ($raw | ForEach-Object { ($_ -replace "`0", "").Trim() } | Where-Object { $_ })
  } catch { return @() }
}

function Ensure-Wsl {
  if (-not (Get-Command wsl.exe -ErrorAction SilentlyContinue)) {
    Write-Host "Enabling the Windows Subsystem for Linux feature..."
    & wsl.exe --install --no-distribution
    Write-Host "WSL was installed. A reboot may be required; re-run this installer afterwards."
    return $false
  }
  $distros = Get-WslDistros
  if ($distros -notcontains $Distro) {
    Write-Host "Installing the $Distro distribution (this downloads a few hundred MB)..."
    & wsl.exe --install -d $Distro --no-launch
  }
  return $true
}

function Invoke-InDistro {
  param([string]$Command)
  & wsl.exe --distribution $Distro --exec bash -lc $Command
  if ($LASTEXITCODE -ne 0) { throw "Command failed inside $Distro (exit $LASTEXITCODE): $Command" }
}

function New-Shortcuts {
  $launcher = Join-Path $env:LOCALAPPDATA "ACOS\Start-ACOS.cmd"
  New-Item -ItemType Directory -Force -Path (Split-Path $launcher) | Out-Null
  $cmd = @"
@echo off
rem Generated by the ACOS Windows installer. Launches the ACOS workspace in WSL2.
wsl.exe --distribution $Distro --exec bash -lc "cd $InstallDir && exec bash src/host/start-local.sh"
if errorlevel 1 (
  echo.
  echo ACOS could not start. See docs/windows.md for troubleshooting.
  pause
)
"@
  Set-Content -Path $launcher -Value $cmd -Encoding ASCII

  $shell = New-Object -ComObject WScript.Shell
  foreach ($dir in @(
      (Join-Path $env:APPDATA "Microsoft\Windows\Start Menu\Programs"),
      ([Environment]::GetFolderPath("Desktop"))
    )) {
    $link = $shell.CreateShortcut((Join-Path $dir "ACOS.lnk"))
    $link.TargetPath = $launcher
    $link.WorkingDirectory = (Split-Path $launcher)
    $link.Description = "Launch the ACOS local AI companion"
    $link.Save()
  }
  Write-Host "Created Start Menu and Desktop shortcuts."
}

function Main {
  Assert-Admin
  Test-Windows11
  if (-not (Ensure-Wsl)) { return }

  Write-Host "Preparing the ACOS checkout inside $Distro..."
  $clone = "if [ -d $InstallDir/.git ]; then cd $InstallDir && git fetch --all && git pull --ff-only; " +
           "elif [ -d $InstallDir ]; then echo 'Existing $InstallDir is not a git checkout; leaving it untouched.'; " +
           "else git clone $RepoUrl $InstallDir; fi"
  Invoke-InDistro $clone

  if (-not $SkipSetup) {
    Write-Host "Running ACOS setup inside $Distro (installs pinned Node/pnpm and dependencies)..."
    Invoke-InDistro "cd $InstallDir && bash src/host/setup-wsl.sh"
  }

  New-Shortcuts
  Write-Host ""
  Write-Host "ACOS is installed." -ForegroundColor Green
  Write-Host "  1. Launch ACOS from the Desktop or Start Menu shortcut."
  Write-Host "  2. Read your administrator key locally:  wsl -d $Distro cat ~/.local/share/acos/admin.key"
  Write-Host "  3. Paste it into the dashboard, open the Local engine panel, and load the model."
  Write-Host ""
  Write-Host "Optional AI engine: run inside Ubuntu ->  cd $InstallDir && pnpm setup:engine"
}

Main
